development:
  adapter: postgresql
  encoding: unicode
  database: kairos_development
  pool: 5
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: kairos_test
  pool: 5
  host: localhost
  template: template0
