development:
  adapter: postgresql
  encoding: unicode
  database: kairos_development
  pool: 5
  username: kairos 
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode  
  database: kairos_test
  pool: 5
  username: kairos 
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode  
  database: kairos_production
  pool: 5
  username: kairos 
  password: